// PBI-081 / TASK-081-3
// 公開ルート単一ソース（routes.ts）と `public/sitemap.xml` 掲載 URL の差分検知。
// CI（vitest）で FAIL 化することで、ルート追加忘れ／sitemap 再生成漏れを構造的に防ぐ。
//
// 設計:
// - `pretest` で `scripts/generate-sitemap.mjs` を実行し public/sitemap.xml を再生成する。
// - 本テストは生成後の `public/sitemap.xml` を読み込み、`PUBLIC_ROUTES` と
//   path / changefreq / priority の集合一致を検証する（順序は問わない）。
// - 受入基準（PBI-081）に対応:
//   * Router 定義を単一ソースとしビルドスクリプトで sitemap.xml を生成する → 生成スクリプト出力を検証
//   * sitemap 掲載 URL と実ルートの不整合を検知するテストを追加し FAIL 時 CI が落ちる

import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PUBLIC_ROUTES, PUBLIC_ROUTE_PATHS } from './routes';

const FRONT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SITEMAP_PATH = resolve(FRONT_DIR, 'public', 'sitemap.xml');
const SITEMAP = readFileSync(SITEMAP_PATH, 'utf-8');
const SITE_URL_TOKEN = '__SITE_URL__';

interface SitemapEntry {
  path: string;
  changefreq: string;
  priority: string;
}

/** sitemap.xml の `<url>` ブロックを抽出して `{ path, changefreq, priority }` 配列に変換する。 */
function parseSitemap(xml: string): SitemapEntry[] {
  const entries: SitemapEntry[] = [];
  const urlRe = /<url>([\s\S]*?)<\/url>/g;
  let m: RegExpExecArray | null;
  while ((m = urlRe.exec(xml)) !== null) {
    const block = m[1];
    const loc = /<loc>([^<]+)<\/loc>/.exec(block)?.[1] ?? '';
    const changefreq = /<changefreq>([^<]+)<\/changefreq>/.exec(block)?.[1] ?? '';
    const priority = /<priority>([^<]+)<\/priority>/.exec(block)?.[1] ?? '';
    // `__SITE_URL__` を剥がして path 形式に正規化（先頭 / を補う）
    let path: string;
    if (loc === SITE_URL_TOKEN) {
      path = '/';
    } else if (loc.startsWith(SITE_URL_TOKEN)) {
      path = `/${loc.slice(SITE_URL_TOKEN.length)}`;
    } else {
      path = loc;
    }
    entries.push({ path, changefreq, priority });
  }
  return entries;
}

describe('PBI-081 sitemap-coverage（routes.ts ↔ public/sitemap.xml 差分検知）', () => {
  const sitemapEntries = parseSitemap(SITEMAP);

  it('sitemap.xml 掲載 URL 件数が PUBLIC_ROUTES と一致する', () => {
    expect(sitemapEntries).toHaveLength(PUBLIC_ROUTES.length);
  });

  it('sitemap.xml の <loc> 集合が PUBLIC_ROUTE_PATHS と完全一致する', () => {
    const sitemapPaths = sitemapEntries.map((e) => e.path);
    expect(new Set(sitemapPaths)).toEqual(new Set(PUBLIC_ROUTE_PATHS));
  });

  it('全 path について changefreq / priority が routes.ts の定義と一致する', () => {
    const byPath = new Map(sitemapEntries.map((e) => [e.path, e]));
    for (const route of PUBLIC_ROUTES) {
      const entry = byPath.get(route.path);
      expect(entry, `sitemap に欠落: ${route.path}`).toBeDefined();
      expect(entry!.changefreq).toBe(route.changefreq);
      expect(Number(entry!.priority)).toBeCloseTo(route.priority, 5);
    }
  });

  it('sitemap.xml の <loc> はすべて __SITE_URL__ トークン始まり（http(s) 直書き 0 件）', () => {
    const locs = [...SITEMAP.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]);
    for (const loc of locs) {
      expect(loc.startsWith(SITE_URL_TOKEN)).toBe(true);
      expect(loc).not.toMatch(/https?:\/\//);
    }
  });

  it('AUTO-GENERATED ヘッダーコメントが残存している（手動編集防止の明示）', () => {
    expect(SITEMAP).toContain('AUTO-GENERATED by scripts/generate-sitemap.mjs');
  });
});
