#!/usr/bin/env node
// PBI-081 / TASK-081-2
// 公開ルート単一ソース（src/routes.ts）から `public/sitemap.xml` を自動生成する。
//
// 設計:
// - 入力: `src/routes.ts` の `PUBLIC_ROUTES` リテラル（regex で安全にパース）
// - 出力: `public/sitemap.xml`（`__SITE_URL__` トークン埋め込みのまま）
// - `__SITE_URL__` 置換は build 末尾の `transform-seo-tokens.mjs` が dist/ 上で実施する
//   （PBI-058 規律：env 依存値はビルド時注入）
//
// CI 上の差分検知は `src/sitemap-coverage.test.ts`（TASK-081-3）が
// `routes.ts` と `public/sitemap.xml` の URL 集合・priority・changefreq を突合し FAIL 化する。

import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const SITE_URL_TOKEN = '__SITE_URL__';
const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONT_DIR = resolve(__dirname, '..');
const ROUTES_TS = resolve(FRONT_DIR, 'src', 'routes.ts');
const OUTPUT = resolve(FRONT_DIR, 'public', 'sitemap.xml');

/**
 * `src/routes.ts` から `PUBLIC_ROUTES` リテラルを抽出して JS 配列に変換する。
 * 各エントリは `{ path: '/...', changefreq: '...', priority: 0.X }` 形式の
 * 単純なリテラル前提（PBI-081 規約）。
 */
async function parsePublicRoutes() {
  const src = await readFile(ROUTES_TS, 'utf-8');
  const blockMatch = src.match(/export const PUBLIC_ROUTES[^=]*=\s*\[([\s\S]*?)\]\s*as const;/);
  if (!blockMatch) {
    throw new Error('[generate-sitemap] PUBLIC_ROUTES の宣言を routes.ts から抽出できませんでした');
  }
  const body = blockMatch[1];
  const entryRe =
    /\{\s*path:\s*'([^']+)'\s*,\s*changefreq:\s*'([^']+)'\s*,\s*priority:\s*([0-9]+\.?[0-9]*)\s*\}/g;
  const routes = [];
  let m;
  while ((m = entryRe.exec(body)) !== null) {
    routes.push({ path: m[1], changefreq: m[2], priority: Number(m[3]) });
  }
  if (routes.length === 0) {
    throw new Error('[generate-sitemap] PUBLIC_ROUTES から 1 件もエントリを抽出できませんでした');
  }
  return routes;
}

/** path を sitemap の `<loc>` 用に `__SITE_URL__` 接続形へ整形する（先頭 / は二重化回避のため除去）。 */
function toLoc(path) {
  if (path === '/') return SITE_URL_TOKEN;
  return `${SITE_URL_TOKEN}${path.startsWith('/') ? path.slice(1) : path}`;
}

/** priority を `<priority>` 表記に正規化（小数点1桁・1.0 維持）。 */
function formatPriority(priority) {
  return priority.toFixed(1);
}

function buildXml(routes) {
  const urls = routes
    .map(
      (r) =>
        `  <url>\n    <loc>${toLoc(r.path)}</loc>\n    <changefreq>${r.changefreq}</changefreq>\n    <priority>${formatPriority(r.priority)}</priority>\n  </url>`,
    )
    .join('\n');
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!--',
    '  AUTO-GENERATED by scripts/generate-sitemap.mjs from src/routes.ts (PBI-081 / TASK-081-2)',
    '  このファイルを直接編集しないこと。ルート追加は src/routes.ts を更新し `pnpm prebuild` を実行する。',
    '  `__SITE_URL__` は build 末尾の transform-seo-tokens.mjs が dist/ 上で置換する。',
    '-->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    '</urlset>',
    '',
  ].join('\n');
}

async function main() {
  const routes = await parsePublicRoutes();
  const xml = buildXml(routes);
  await writeFile(OUTPUT, xml, 'utf-8');
  console.log(`[generate-sitemap] wrote ${routes.length} routes -> ${OUTPUT}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
